name: a03_farming
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  http: ^0.13.4
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png" # fallback for non-adaptive devices
  adaptive_icon_background: "#000000"    # or an image: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/crops/
    - assets/images/weather_icons/