// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAq1nLRByJj0-xZYkxI1XvjnMpc8SauE',
    appId: '1:967602030648:web:23c8f18aed0f7044e87ecd',
    messagingSenderId: '967602030648',
    projectId: 'a03farming',
    authDomain: 'a03farming.firebaseapp.com',
    storageBucket: 'a03farming.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSCZdSTCalDZifalD3IXhdLLjZGasWfw',
    appId: '1:967602030648:android:c7f8ed126a017d1fe87ecd',
    messagingSenderId: '967602030648',
    projectId: 'a03farming',
    storageBucket: 'a03farming.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5LWWeVmT8rCOlFf9ktyGDvcaf7kLg5M',
    appId: '1:967602030648:ios:4820ae0a68a2164de87ecd',
    messagingSenderId: '967602030648',
    projectId: 'a03farming',
    storageBucket: 'a03farming.firebasestorage.app',
    iosBundleId: 'com.example.a03Farming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5LWWeVmT8rCOlFf9ktyGDvcaf7kLg5M',
    appId: '1:967602030648:ios:4820ae0a68a2164de87ecd',
    messagingSenderId: '967602030648',
    projectId: 'a03farming',
    storageBucket: 'a03farming.firebasestorage.app',
    iosBundleId: 'com.example.a03Farming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAq1nLRByJj0-xZYkxI1XvjnMpc8SauE',
    appId: '1:967602030648:web:c9dcb9626bf5464ae87ecd',
    messagingSenderId: '967602030648',
    projectId: 'a03farming',
    authDomain: 'a03farming.firebaseapp.com',
    storageBucket: 'a03farming.firebasestorage.app',
  );

}